[package]
name = "galdisasm"
version = "0.1.0"
authors = ["Mike Walters <mike@flomp.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
